### PR TITLE
This closes hex-sticker issue #1

### PR DESCRIPTION
**Pull request by martincadek**
Updated logo script to close issue #1 . (_I hope I did the pull request correctly, apologies if not as I don't have experience with contributing to other people's repositories. I forked it, created my hex branch and kept the master intact._)

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Look good, can we see the end result?

**Review by Robinlovelace — APPROVED** [review]

**Comment by martincadek** [comment]
rleeds_hex_logo

The code should output this. Fonts were changed because url was printed weirdly with mono fonts and sadly the text arranging with the package allows only modification on x and y axis. Maybe there other way to arrange it.

**Comment by Robinlovelace** [comment]
Looks good to me, I approve! In interests of not jumping the gun this time, does this look good to you @eddjberry ?

**Comment by eddjberry** [comment]
Good work. Is there a way to make the curves a bit more smooth? I guess it'd just be a case of upping the resolution or making them thinner. That said, no one's going to be looking at it that big! 

Looking at other people's hex stickers they seem to save them small with high resolution. I'll have a quick play, if you like.

**Comment by Robinlovelace** [comment]
Good plan to iterate.

**Comment by eddjberry** [comment]
I'm going to merge this into the branch here so I can pull it down and then we can have a separate PR to master

**Comment by martincadek** [comment]
> 
> 
> Good work. Is there a way to make the curves a bit more smooth? I guess it'd just be a case of upping the resolution or making them thinner. That said, no one's going to be looking at it that big!
> 
> Looking at other people's hex stickers they seem to save them small with high resolution. I'll have a quick play, if you like.

Thanks. Yes, go ahead and play around with this. 

I think you can make them thinner to improve the smoothing or try alternative outputs but I don't know how far you can stretch the package (it seemed to support .png only). Increasing resolution should work too and perhaps even changing the smoothing functions or using different plotting system beside ggplot2. 

I would probably first try to simply minimise it as the sticker is quite big here and normally they look smaller - [stickers](https://github.com/GuangchuangYu/hexSticker#stickers-for-software-packages).

**Pull request merged**
